

# _config.yml

title: "Pragya Sharma's Portfolio"
description: "Showcasing my work and projects"
baseurl: ""  # Leave empty unless you're using GitHub Pages with a custom subdomain

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"


#theme
remote_theme: pages-themes/tactile@v0.2.0

# Author Information
author:
  name: "Your Name"
  email: "you@example.com"

# Social Media Links
social_links:
  twitter: "https://twitter.com/yourhandle"
  github: "https://github.com/yourusername"
  linkedin: "https://www.linkedin.com/in/yourname"

# Build settings
markdown: kramdown
